// Emoticons map: text pattern → emoji shortCode
// Only used when options.emoticons = true
export const EMOTICONS: Record<string, string> = {
	':)': 'slight_smile',
	':-)': 'slight_smile',
	':]': 'slight_smile',
	'=)': 'slight_smile',
	':((': 'cry',
	':(': 'disappointed',
	':-(': 'disappointed',
	':[': 'disappointed',
	'=(': 'disappointed',
	':D': 'smiley',
	':-D': 'smiley',
	'=D': 'smiley',
	';)': 'wink',
	';-)': 'wink',
	':P': 'stuck_out_tongue',
	':-P': 'stuck_out_tongue',
	'=P': 'stuck_out_tongue',
	':p': 'stuck_out_tongue',
	':-p': 'stuck_out_tongue',
	':O': 'open_mouth',
	':-O': 'open_mouth',
	':o': 'open_mouth',
	':-o': 'open_mouth',
	':|': 'neutral_face',
	':-|': 'neutral_face',
	":'(": 'cry',
	'>:(': 'angry',
	'>:-(': 'angry',
	'B)': 'sunglasses',
	'B-)': 'sunglasses',
	'8)': 'sunglasses',
	'8-)': 'sunglasses',
	':3': 'cat',
	':/': 'confused',
	':-/': 'confused',
	'D:': 'fearful',
	'O:)': 'innocent',
	'O:-)': 'innocent',
	':*': 'kissing_heart',
	':-*': 'kissing_heart',
	':^)': 'slight_smile',
	'¯\\_(ツ)_/¯': 'shrug',
};

// Build sorted list (longest first to avoid partial matches)
export const EMOTICON_LIST = Object.keys(EMOTICONS).sort((a, b) => b.length - a.length);
